name: fmm
favicon: null
layout_spectrum: 0.22157
typography_spectrum: 0.83863
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.875
  lightness: 0.08935201750136912
  saturation: 0.07026059716008604
  rhythmicContrast: 0.6584963384084404
purpose: []
